<script src="/ckeditor/ckeditor.js"></script>
<script src="/ckfinder/ckfinder.js"></script>

<script>
    $(document).ready(function () {
        CKEDITOR.replace('news[full_text]', {
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html?Type=Images',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html?Type=Flash',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
        });
    });
</script>

<legend>Редактировать новость</legend>

<?php if (isset($this->exception_msg)): ?>
    <div class="alert alert-error">
        <h4 class="alert-heading">Ошибка!</h4>
        <?php echo $this->escape($this->exception_msg); ?>
    </div>
<?php endif; ?>

<?php echo $this->form; ?>