<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Объединение управляющих компаний Кемеровской области</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/js/jqueryui/css/smoothness/jquery-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/main.css">

    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" language="javascript" src="/js/jqueryui/jquery-ui.min.js"></script>
    <script type="text/javascript" language="javascript" src="/js/i18n/jquery.ui.datepicker-ru.js"></script>
    <script type="text/javascript" language="javascript" src="/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/js/main.js"></script>
</head>
<body>

<div class="wrapper">
    <div class="header">

        <div class="main_menu">
            <ul class="menu">
                <li><a href="/" title="Главная">Главная</a></li>
                <?php $firstItem = true; ?>
                <?php if ($this->topMenuList != false): ?>
                    <?php foreach ($this->topMenuList as $item): ?>
                        <?php if ($item->isVisible): ?>
                            <li <?php if ($firstItem):
                                $firstItem = false; ?>class="first"<?php endif; ?> >
                                <a href="<?php if ($item->hasChild()): ?>#<?php else: ?> <?php echo $this->escape($item->getUrl($this->authUserRole)); ?><?php endif; ?>"><?php echo $this->escape($item->title) ?></a>
                                <?php if ($item->hasChild()): ?>
                                    <?php echo $this->partial('_submenu.phtml', array('itemList' => $item->getChild(), 'authUserRole' => $this->authUserRole)); ?>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if ($this->authUserRole !== 'guest'): ?>
                    <li>
                        <a href="#" title="Управление">Управление</a>
                        <ul>
                            <li><a href="/menu/">Меню</a></li>
                            <li><a href="/contentpage/">Контентные страницы</a></li>
                            <li><a href="/phone/">Телефоны</a></li>
                            <li><a href="/user/">Пользователи</a></li>
                            <li><a href="/login/logout/"><?php echo $this->authUser; ?> (выход)</a></li>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>


    <?php echo $this->layout()->content; ?>

    <div class="footer">
        <p></p>

        <p>e-mail: <a href="mailto:" title="Отправить письмо по электронной почте"></a></p>

        <p></p>
    </div>
</div>

</body>
</html>