<div class="content">

    <legend><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Точки приема платежей<?php endif; ?></legend>

    <?php if (isset($this->exception_msg)): ?>
        <div class="alert alert-error">
            <h4 class="alert-heading">Ошибка!</h4>
            <?php echo $this->escape($this->exception_msg); ?>
        </div>
    <?php endif; ?>

    <a href="<?php echo $this->url(array('controller' => 'payment-point', 'action' => 'add', 'link' => $this->escape($this->link))) ?>"><i class="icon-plus"></i>Добавить точку</a><br /><br />


    <table class="table table-bordered">
        <tr>
            <th>Фото</th>
            <th>Название</th>
            <th>Адрес</th>
            <th>Действия</th>
        </tr>

        <?php if ($this->pointList !== false): ?>
            <?php foreach ($this->pointList as $item): ?>
                <tr>
                    <td><img src="/files<?php echo $this->escape($item->file->getSubPath()); ?>/<?php echo $this->escape($item->file->getPreview()); ?>" title="<?php echo $this->escape($item->title); ?>" alt="<?php echo $this->escape($item->title); ?>"/></td>
                    <td><?php echo $this->escape($item->title); ?></td>
                    <td><?php echo $this->escape($item->address); ?></td>
                    <td class="tedit">
                        <a href="<?php echo $this->url(array('controller' => 'payment-point', 'action' => 'edit', 'id' => $item->id, 'link' => $this->escape($this->link))); ?>"><i class="icon-pencil"></a>
                        <a href="<?php echo $this->url(array('controller' => 'payment-point', 'action' => 'delete', 'id' => $item->id, 'link' => $this->escape($this->link))); ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');"><i class="icon-remove"></i></a>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>

    <div class="clear"></div>
</div>