<div class="content">
    <div class="news">
        <div class="n_title">
            <a href="#" title="<?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Точки приема платежей<?php endif; ?>"><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Точки приема платежей<?php endif; ?></a>
        </div>

        <?php if ($this->pointList !== false): ?>
            <?php foreach ($this->pointList as $item): ?>
                <div class="one_item">
                    <div class="item_image">
                        <?php if ($item->file->getName()): ?>
                            <a href="<?php echo $this->url(array('controller' => 'payment-point', 'action' => 'viewpoint', 'id' => $item->id), $this->linkInfo->getFullUrl('-') . '-viewpoint'); ?>" title="<?php echo $this->escape($item->title); ?>">
                                <img src="/files<?php echo $this->escape($item->file->getSubPath()); ?>/<?php echo $this->escape($item->file->getPreview()); ?>" title="<?php echo $this->escape($item->title); ?>" alt="<?php echo $this->escape($item->title); ?>" />
                            </a>
                        <?php endif; ?>
                    </div>

                    <div class="item_right">
                        <p class="item_title">
                            <a href="<?php echo $this->url(array('controller' => 'payment-point', 'action' => 'viewpoint', 'id' => $item->id), $this->linkInfo->getFullUrl('-') . '-viewpoint') ?>" title=""><?php echo $this->escape($item->title); ?></a>
                        </p>

                        <p class="item_shortcontent"><?php echo $this->escape($item->address); ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>